Catch certbot: command not found error

diff --git a/scripts/rtletsencrypt b/scripts/rtletsencrypt
--- a/scripts/rtletsencrypt
+++ b/scripts/rtletsencrypt
@@ -100,6 +100,9 @@ if [ -s $logencrypt ]; then
     if [[ $line == *"Challenge failed for domain"* ]]; then
       echo "unable to generate certificates"
       exit 1
+    elif [[ $line == *"command not found"* ]]; then
+      echo "unable to generate certificates"
+      exit 1
     fi
   done < $logencrypt
 else
